from pathlib import Path

DEFAULT_MODEL_ID = "Qwen/Qwen3-TTS-12Hz-1.7B-Base"
DEFAULT_DEVICE = "cpu"
DEFAULT_DTYPE = "float32"
DEFAULT_LOW_CPU_MEM_USAGE = True
DEFAULT_CPU_THREADS = None
DEFAULT_CPU_INTEROP_THREADS = 1
DEFAULT_LANGUAGE = "Auto"
DEFAULT_MAX_NEW_TOKENS = 1024
DEFAULT_TIMEOUT_SEC = 300
DEFAULT_MAX_RETRIES = 2
DEFAULT_SPLIT_MAX_CHARS = 180
MIN_REF_AUDIO_SEC = 2.5

RUNTIME_ROOT = Path("runtime")
VOICES_DIRNAME = "voices"
JOBS_DIRNAME = "jobs"
OUTPUT_DIRNAME = "output"
LOGS_ROOT = Path("logs")
QUEUE_DB_NAME = "queue.sqlite3"
